#!/usr/bin/env python3
"""Decode the double-extended constants from Intel's ia64 sincosl.s
(glibc sysdeps/ia64/fpu/s_cosl.S, tag glibc-2.38) into exact values, and
measure each kernel coefficient's deviation from the corresponding Taylor
coefficient (showing the Remez/minimax adjustment).

All arithmetic is exact (Fraction / integer); no host floating point is used
except for final display of approximate decimal values.
"""
from fractions import Fraction
from math import factorial

# ---------------------------------------------------------------- constants
# (name, mantissa_hex, signexp_hex) exactly as in the .S data tables.
RAW = [
    # sincosl_table_p
    ("Inv_pi_by_2", 0xA2F9836E4E44152A, 0x3FFE),
    ("P_0",         0xC84D32B0CE81B9F1, 0x4016),
    ("P_1",         0xC90FDAA22168C235, 0x3FFF),
    ("P_2",         0xECE675D1FC8F8CBB, 0xBFBD),
    ("P_3",         0xB7ED8FBBACC19C60, 0xBF7C),
    ("d_1",         0x8D848E89DBD171A1, 0xBFBF),
    ("d_2",         0xD5394C3618A66F8E, 0xBF7C),
    # sincosl_table_d
    ("pi_by_4",     0xC90FDAA22168C234, 0x3FFE),
    ("Inv_P_0",     0xA397E5046EC6B45A, 0x3FE7),
    # sincosl_table_pp (sine kernel, normal_r: r + PP_1 r^3 + ... + PP_8 r^17)
    ("PP_1_hi",     0xAAAA000000000000, 0xBFFC),
    ("PP_1_lo",     0xAAAAAAAAAAAB0000, 0xBFEC),
    ("PP_2",        0x8888888888888962, 0x3FF8),
    ("PP_3",        0xD00D00D00D03BB69, 0xBFF2),
    ("PP_4",        0xB8EF1D2ABAF69EEA, 0x3FEC),
    ("PP_5",        0xD7322B47D1EB75A4, 0xBFE5),
    ("PP_6",        0xB092382F640AD517, 0x3FDE),
    ("PP_7",        0xD7468A05720221DA, 0xBFD6),
    ("PP_8",        0xCC8ABEBCA21C0BC9, 0x3FCE),
    # sincosl_table_qq (cosine kernel, normal_r: 1 + QQ_1 r^2 + ... + QQ_8 r^16)
    ("QQ_1",        0x8000000000000000, 0xBFFE),
    ("QQ_2",        0xAAAAAAAAAAAAAA9B, 0x3FFA),
    ("QQ_3",        0xB60B60B60B607F60, 0xBFF5),
    ("QQ_4",        0xD00D00D00C6E5041, 0x3FEF),
    ("QQ_5",        0x93F27DBAFDA8D0FC, 0xBFE9),
    ("QQ_6",        0x8F76C6509C716658, 0x3FE2),
    ("QQ_7",        0xC9C99ABA2B48DCA6, 0xBFDA),
    ("QQ_8",        0xD56232EFC2B0FE52, 0x3FD2),
    # sincosl_table_s (small_r sine: r + S_1 r^3 + ... + S_5 r^11)
    ("S_1",         0xAAAAAAAAAAAAAAAA, 0xBFFC),
    ("S_2",         0x88888888888868DB, 0x3FF8),
    ("S_3",         0xD00D00D0055EFD4B, 0xBFF2),
    ("S_4",         0xB8EF1C5D839730B9, 0x3FEC),
    ("S_5",         0xD71EA3A4E5B3F492, 0xBFE5),
    # sincosl_table_c (small_r cosine: 1 + C_1 r^2 + ... + C_5 r^10)
    ("C_1",         0xFFFFFFFFFFFFFFFE, 0xBFFD),
    ("C_2",         0xAAAAAAAAAAAA719F, 0x3FFA),
    ("C_3",         0xB60B60B60356F994, 0xBFF5),
    ("C_4",         0xD00CFFD5B2385EA9, 0x3FEF),
    ("C_5",         0x93E4BD18292A14CD, 0xBFE9),
]

def decode(mant, signexp):
    sign = -1 if (signexp & 0x8000) else 1
    exp = signexp & 0x7FFF
    return Fraction(sign * mant, 1) * Fraction(2) ** (exp - 16383 - 63)

# ------------------------------------------------- high-precision pi (exact)
def pi_fraction(prec_bits=400):
    """Machin: pi = 16 atan(1/5) - 4 atan(1/239), as an exact Fraction with
    error < 2^-prec_bits."""
    def atan_inv(n):
        # atan(1/n) = sum_{k>=0} (-1)^k / ((2k+1) n^(2k+1))
        total = Fraction(0)
        k = 0
        while True:
            term = Fraction((-1) ** k, (2 * k + 1) * n ** (2 * k + 1))
            total += term
            if abs(term) < Fraction(1, 2 ** (prec_bits + 16)):
                return total
            k += 1
    return 16 * atan_inv(5) - 4 * atan_inv(239)

PI = pi_fraction()

# Taylor coefficient of the sine kernel term r^(2k+1): (-1)^k/(2k+1)!
def sin_taylor(k):  return Fraction((-1) ** k, factorial(2 * k + 1))
# Taylor coefficient of the cosine kernel term r^(2k): (-1)^k/(2k)!
def cos_taylor(k):  return Fraction((-1) ** k, factorial(2 * k))

def ulp_of(frac_val):
    """ulp size of a 64-bit-significand number with the magnitude of val."""
    if frac_val == 0:
        return None
    a = abs(frac_val)
    # find e with 2^e <= a < 2^(e+1)
    e = a.numerator.bit_length() - a.denominator.bit_length()
    if Fraction(2) ** e > a:
        e -= 1
    assert Fraction(2) ** e <= a < Fraction(2) ** (e + 1)
    return Fraction(2) ** (e - 63)

def fdec(frac, digits=25):
    """approximate decimal string of a Fraction (round-half-even-ish)."""
    sign = "-" if frac < 0 else ""
    a = abs(frac)
    scaled = a * 10 ** digits
    i = scaled.numerator // scaled.denominator
    s = str(i).rjust(digits + 1, "0")
    return f"{sign}{s[:-digits]}.{s[-digits:]}"

vals = {name: decode(m, se) for name, m, se in RAW}

out = []
out.append("# Decoded constants — Intel ia64 sincosl.s (glibc-2.38)\n")
out.append("Generated by `src/decode_constants.py` (exact rational arithmetic).\n")

# --- reduction constants vs. exact pi ---
out.append("## Reduction constants vs. exact value\n")
out.append("| name | exact stored value (approx decimal) | reference | stored − ref (in ulps of stored) |")
out.append("|---|---|---|---|")
refs = {
    "Inv_pi_by_2": 2 / PI,
    "P_1":  PI / 2,
    "pi_by_4": PI / 4,
}
for name in ("Inv_pi_by_2", "P_0", "P_1", "P_2", "P_3", "d_1", "d_2",
             "pi_by_4", "Inv_P_0"):
    v = vals[name]
    if name in refs:
        r = refs[name]
        du = (v - r) / ulp_of(v)
        out.append(f"| {name} | {fdec(v)} | exact | {float(du):+.4f} |")
    else:
        out.append(f"| {name} | {fdec(v)} | (composite, see below) | |")

# multi-piece checks: P_1+P_2+P_3 should be ~ pi/2 to much higher precision
p123 = vals["P_1"] + vals["P_2"] + vals["P_3"]
err = (p123 - PI / 2)
out.append("")
out.append(f"- `P_1 + P_2 + P_3 − π/2` = {fdec(err, 40)} "
           f"(≈ 2^{(err and (abs(err).numerator.bit_length() - abs(err).denominator.bit_length())) or 'exact'})")
# P_0 relationship: header says Step 8 pre-reduction: Arg' = Arg - N_0*P_0,
# with Inv_P_0 its reciprocal; P_0 should be a big multiple of pi/2.
ratio = vals["P_0"] / (PI / 2)
out.append(f"- `P_0 / (π/2)` = {fdec(ratio, 10)}  (≈ integer multiple of π/2)")
k = round(ratio)
# Step 8 computes Arg' := Arg − N_0·P_0 and then ADDS w := N_0·d_1 (+ N_0·d_2
# in Case 4), so the effective modulus is P_0 − d_1 − d_2 (d_1, d_2 are stored
# negative). Verify that identity:
p0d = vals["P_0"] - vals["d_1"] - vals["d_2"]
err0 = p0d - k * PI / 2
out.append(f"- nearest integer: {k}; `(P_0 − d_1 − d_2) − {k}·π/2` = {fdec(err0, 40)}")
inv_check = vals["Inv_P_0"] * vals["P_0"]
out.append(f"- `Inv_P_0 · P_0` = {fdec(inv_check, 25)} (≈1 check)")
invpi_check = vals["Inv_pi_by_2"] * PI / 2
out.append(f"- `Inv_pi_by_2 · π/2` = {fdec(invpi_check, 25)} (≈1 check)")

# --- kernel coefficients vs Taylor ---
def kernel_table(title, names, taylor, first_k):
    out.append(f"\n## {title}\n")
    out.append("| name | exact stored value (approx decimal) | Taylor ref | (stored − Taylor) in ulps of stored |")
    out.append("|---|---|---|---|")
    for i, name in enumerate(names):
        v = vals[name]
        t = taylor(first_k + i)
        du = (v - t) / ulp_of(v)
        out.append(f"| {name} | {fdec(v)} | {t.numerator}/{t.denominator} | {float(du):+.3f} |")

# PP_1 = PP_1_hi + PP_1_lo, compare combined to -1/6, then the split pieces raw
out.append("\n## Sine kernel PP (normal_r, degree 17): r + PP_1·r³ + PP_2·r⁵ + … + PP_8·r¹⁷\n")
pp1 = vals["PP_1_hi"] + vals["PP_1_lo"]
t = sin_taylor(1)
out.append(f"- `PP_1_hi` = {fdec(vals['PP_1_hi'])} (16-bit mantissa piece: exact-product engineering)")
out.append(f"- `PP_1_lo` = {fdec(vals['PP_1_lo'])}")
out.append(f"- `PP_1_hi + PP_1_lo` = {fdec(pp1)} vs −1/6: diff = "
           f"{float((pp1 - t) / ulp_of(pp1)):+.3f} ulps(PP_1)")
out.append("")
out.append("| name | exact stored value (approx decimal) | Taylor ref | (stored − Taylor) in ulps of stored |")
out.append("|---|---|---|---|")
for i, name in enumerate(["PP_2", "PP_3", "PP_4", "PP_5", "PP_6", "PP_7", "PP_8"]):
    v = vals[name]
    tt = sin_taylor(i + 2)
    out.append(f"| {name} | {fdec(v)} | {tt.numerator}/{tt.denominator} | {float((v - tt) / ulp_of(v)):+.3f} |")

kernel_table("Cosine kernel QQ (normal_r, degree 16): 1 + QQ_1·r² + … + QQ_8·r¹⁶",
             ["QQ_1", "QQ_2", "QQ_3", "QQ_4", "QQ_5", "QQ_6", "QQ_7", "QQ_8"],
             cos_taylor, 1)
kernel_table("Small-r sine S (degree 11): r + S_1·r³ + … + S_5·r¹¹",
             ["S_1", "S_2", "S_3", "S_4", "S_5"], sin_taylor, 1)
kernel_table("Small-r cosine C (degree 10): 1 + C_1·r² + … + C_5·r¹⁰",
             ["C_1", "C_2", "C_3", "C_4", "C_5"], cos_taylor, 1)

out.append("""
## Reading the deviations

A coefficient exactly equal to its Taylor value shows 0 ulps. Remez/minimax
fits show small but *systematic* deviations, largest at the tail (highest
degree), because the fit redistributes the truncation error across the
interval. The hi/lo split of PP_1 and the 2-ulp-shy C_1 are *engineering*
choices (exactness of products), not fit artifacts.
""")

print("\n".join(out))
